### PR TITLE
feat: fetch customer notes from a Shipstation order

### PR DESCRIPTION
**Pull request by Alchez**
**Sales Order:**

image

**Sales Order Item:**

image

### CODE REVIEW

**Comment by vjFaLk** [comment]
@Alchez I know that this isn't in the current scope, but I remember there being per-item notes as well for Custom Items, can yo pull those into the items table too?

**Comment by Alchez** [comment]
@vjFaLk, do we have an example order(s) for per-item notes? I could see which fields to pull based on that.

**Comment by vjFaLk** [comment]
@Alchez I don't have one off the top of my head but if you go through the opencart orders for FPS you will find something.

**Comment by vjFaLk** [comment]
Task linked: [CU-17ny578 FPS: Notes coming in from Opencart via ShipStation](https://app.clickup.com/t/17ny578)

**Comment by Alchez** [comment]
@vjFaLk, there seems to be a "Description" field per item that FPS seems to use for additional notes. They vary between order and item notes, so I'm not sure if this is the field we want, but we can confirm with FPS.

**Comment by vjFaLk** [comment]
@Alchez unless there's a different field with data we should just fetch this

**Comment by vjFaLk** [comment]
@Alchez pls fix conflicts

**Pull request merged**
