### PR TITLE
fix: store name to show up in sales documents 

### PR DESCRIPTION
**Pull request by Alchez**

### CODE REVIEW

**Comment by vjFaLk** [comment]
Task linked: [CU-p76wy7 Improve the Attribution of Sales seen in ShipStation](https://app.clickup.com/t/p76wy7)

**Comment by vjFaLk** [comment]
@Alchez we need a patch for this... We can't run it sync, but we could enqueue a function in the patch instead?

**Comment by Alchez** [comment]
> @Alchez we need a patch for this... We can't run it sync, but we could enqueue a function in the patch instead?

Oh right, patches lol. My only concern with enqueuing patches is that we'll have to manually check if it succeeded or failed :sweat_smile: 

I was thinking a single update query to do it, let me see how much time it takes.

**Comment by vjFaLk** [comment]
@Alchez won't we have to query the API for that data? If we can get all the data in a single query, then it's fine. But otherwise that patch will take a long long time.

**Comment by Alchez** [comment]
@vjFaLk We don't need to go to the API for this, both the values should be available in the Shipstation Settings table

**Comment by Alchez** [comment]
@vjFaLk As discussed, let's let this pass through, and I'll give you the patch logic to rerun on FPS and FTF.

**Comment by vjFaLk** [comment]
The `before_migrate` hook is really taking quite some time

**Comment by Alchez** [comment]
@vjFaLk, we can remove the before_migrate hook. It was just a way to avoid manually re-running the custom field addition for the new field(s).

**Pull request merged**
